services:
  - docker

script:
- docker run --name build-container -dit osrf/ros2:bouncy-ros-base /bin/bash
- docker exec build-container /bin/bash -c 'mkdir -p /ros2_ws/src'
- docker exec build-container /bin/bash -c 'apt update && apt install -y python3-colcon-common-extensions python-rosdep git && rosdep init && rosdep update'
- docker cp $TRAVIS_BUILD_DIR build-container:/ros2_ws/src/
- docker exec build-container /bin/bash -c 'cd /ros2_ws/src && git clone https://github.com/ament/ament_lint.git && git clone https://github.com/ament/ament_cmake.git && git clone https://github.com/ament/ament_pacakge.git'
- docker exec build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && cd /ros2_ws/ && rosdep install --from-paths src --ignore-src --rosdistro bouncy -r -y'
- docker exec build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && cd /ros2_ws/ && colcon build --symlink-install'
- docker exec build-container /bin/bash -c 'source /opt/ros/bouncy/setup.bash && cd /ros2_ws/ && colcon test'
